name: PortalCalc
version: ${project.version}
main: net.mcpueblo.portalcalc.PortalCalc
api-version: 1.13
authors: [JuanDelPueblo]
description: MCPueblo PortalCalc
website: mcpueblo.net
commands:
  portalcalc:
    description: Calculates nether portal location
    usage: /<command>
